
export default {  
    ToggleOption: 'Please toggle an option',
    Encode: 'ENCODE',
    Decode: "DECODE",
    Learn: "LEARN",
    Settings: "SETTINGS",
    EncodeHeader: "Convert text to morse code",
    DecodeHeader: "Convert morse code to text",
    Language: 'Language',
    UseFlash: "Use Flashlight",
    UseSound: "Use Sound",
    UseVib: "Use Vibration",
    Speed: "Speed",
    TextPlaceholder: "Please enter some text",
    DecodePlaceholder: "Please enter morse code",
    Convert: "Convert",
    Stop: "Stop",
    LiveTextMorse: "Live Text to Morse",
    Clear: "Clear",
    MorseToText: "Morse to Text",
    FromString: "From string",
    WithCamera: "With camera",
    WithMic: "With microphone",
    Step: "Step",
    LearnTitle: "Level",
    Complete: "Completion",
    Notification: "Notification",
    SmsNot: "SMS Notification",
    EmailNot: "Email Notification",
    LangChange: "Dil ayarınız kayıt edilmiştir. Bir sonraki açılışta gerçekleşecektir.",
    Tutorial0a: "Click the button under to write dot",
    Tutorial0b: "You need to press the button for less than 200 miliseconds",
    Tutorial1a: "Hold the button a bit to write dash",
    Tutorial1b: "You need to hold the button for less than 1 seconds",
    Tutorial2a: "",
    Tutorial2b: "",
    Tutorial3a: "",
    Tutorial3b: "",
    Tutorial4a: "",
    Tutorial4b: "",
    Tutorial5a: "",
    Tutorial5b: "",
};