
export default {  
    ToggleOption: 'Please toggle an option',
    Encode: 'ENCODE',
    Decode: "DECODE",
    Learn: "LEARN",
    Settings: "SETTINGS",
    EncodeHeader: "Convert text to morse code",
    DecodeHeader: "Convert morse code to text",
    Language: 'Language',
    UseFlash: "Use Flashlight",
    UseSound: "Use Sound",
    UseVib: "Use Vibration",
    Speed: "Speed",
    TextPlaceholder: "Please enter some text",
    Convert: "Convert",
    Stop: "Stop",
    LiveTextMorse: "Live Text to Morse",
    Clear: "Clear",
    MorseToText: "Morse to Text",
    FromString: "From string",
    WithCamera: "With camera",
    WithMic: "With microphone",
    Step: "Step",
    LearnTitle: "Level",
    Complete: "Completion",
    Notification: "Notification",
    SmsNot: "SMS Notification",
    EmailNot: "Email Notification",
    LangChange: "Dil ayarınız kayıt edilmiştir. Bir sonraki açılışta gerçekleşecektir."
};