
export default {  
    ToggleOption: 'Lütfen bir seçenek giriniz',
    Encode: 'KODLA',
    Decode: "ÇÖZ",
    Learn: "ÖĞREN",
    Settings: "AYARLAR",
    EncodeHeader: "Yazıyı mors koduna çevir",
    DecodeHeader: "Mors kodunu yazıya çevir",
    Language: 'Dil',
    UseFlash: "Flash Kullan",
    UseSound: "Ses Kullan",
    UseVib: "Titreşim Kullan",
    Speed: "Hız",
    TextPlaceholder: "Lütfen metin giriniz",
    DecodePlaceholder: "Mors kodu giriniz",
    Convert: "Çevir",
    Stop: "Dur",
    LiveTextMorse: "Gerçek Zamanlı Mors Kodu",
    Clear: "Sil",
    MorseToText: "Metin Karşılğı",
    FromString: "Metinden",
    WithCamera: "Kamera ile",
    WithMic: "Mikrofon ile",
    Step: "Adım",
    LearnTitle: "Seviye",
    Complete: "Bitirme",
    Notification: "Bildirim",
    SmsNot: "SMS Bildirimleri",
    EmailNot: "Email Bildirimleri",
    LangChange: "It's going to activate at the next start."
};