
export default {  
    ToggleOption: 'Lütfen bir seçenek giriniz',
    Encode: 'KODLA',
    Decode: "ÇÖZ",
    Learn: "ÖĞREN",
    Settings: "AYARLAR",
    EncodeHeader: "Yazıyı mors koduna çevir",
    DecodeHeader: "Mors kodunu yazıya çevir",
    Language: 'Dil',
    UseFlash: "Flash Kullan",
    UseSound: "Ses Kullan",
    UseVib: "Titreşim Kullan",
    Speed: "Hız",
    TextPlaceholder: "Lütfen metin giriniz",
    DecodePlaceholder: "Mors kodu giriniz",
    Convert: "Çevir",
    Stop: "Dur",
    LiveTextMorse: "Gerçek Zamanlı Mors Kodu",
    Clear: "Sil",
    MorseToText: "Metin Karşılğı",
    FromString: "Metinden",
    WithCamera: "Kamera ile",
    WithMic: "Mikrofon ile",
    Step: "Adım",
    LearnTitle: "Seviye",
    Complete: "Bitirme",
    Notification: "Bildirim",
    SmsNot: "SMS Bildirimleri",
    EmailNot: "Email Bildirimleri",
    LangChange: "It's going to activate at the next start.",
    Tutorial0a: "Alttaki butona tıklayarak nokta yazabilirsiniz",
    Tutorial0b: "Butona 200 milisaniyeden daha az basmalısınız",
    Tutorial1a: "Butona biraz basılı tutarak çizgi yazabilirsiniz",
    Tutorial1b: "Butonu bir saniyeden az basılı tutmalısınız",
    Tutorial2a: "",
    Tutorial2b: "",
    Tutorial3a: "",
    Tutorial3b: "",
    Tutorial4a: "",
    Tutorial4b: "",
    Tutorial5a: "",
    Tutorial5b: "",
};